[workspace]
members = [
    "color",
    "convert",
    "staff",
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
