[package]
name = "daem"
version = "0.1.0"
edition = "2021"
authors = ["nano <nanoqsh@gmail.com>"]
description = "The dae format converter"

[dependencies]
clap = { version = "4.1.11", default-features = false, features = ["derive", "help", "std"] }
dae-parser = "0.8.8"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
