[package]
name = "staff"
version = "0.1.0"
edition = "2021"

[dependencies]
atlas = { path = "../atlas" }
color = { path = "../color" }
convert = { path = "../convert" }
clap = { version = "4.1", default-features = false, features = [
    "derive",
    "help",
    "std",
] }
serde_json = "1.0"
