[package]
name = "color"
version = "0.1.0"
edition = "2021"

[dependencies]
im = { path = "../im" }
palette = { version = "0.7", default-features = false, features = ["std"] }
serde = { workspace = true }

[lints]
workspace = true
